apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            value: BACKEND_URL # `pragma: allowlist secret`
        volumeMounts:
          - mountPath: /app
            name: frontend-volume
          - mountPath: /app/build
            name: frontend-build
        command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
