apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "dbname"
          - name: POSTGRES_PRIMARY_HOST
            value: "postgres-primary"
          - name: POSTGRES_PRIMARY_PORT
            value: "5432"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-replica-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
spec:
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: postgres-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
