services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      # - ./backend/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres-primary:5432/dbname
      - REACT_APP_API_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./.env
    # entrypoint: ["bash", "/usr/local/bin/entrypoint.sh"]
    command: bash -c "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/photos"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s