services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker compose build backend
    # startCommand: docker compose up backend
    envVars:
      - key: PORT
        value: 8000

