apiVersion: v1
data:
  entrypoint.sh: |
    #! bin/bash/

    echo "Starting DJANGO backend Servce - REACT_APP_NGROK_PUBLIC_URL: $REACT_APP_NGROK_PUBLIC_URL"

    exec "$@"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: backend
  name: backend-cm1
