apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out ./k8s-manifests
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres-replica
  name: postgres-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-replica
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out ./k8s-manifests
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres-replica
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: replicadb
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_PRIMARY_HOST
              value: postgres_primary
            - name: POSTGRES_PRIMARY_PORT
              value: "5432"
            - name: POSTGRES_REPLICATION_PASSWORD
            - name: POSTGRES_REPLICATION_USER
              value: replication_user
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13
          name: postgres-replica
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              memory: "4294967296"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-replica
            - mountPath: /docker-entrypoint-initdb.d/init_replica.sh
              name: postgres-replica-cm1
              subPath: init_replica.sh
      restartPolicy: Always
      volumes:
        - name: postgres-data-replica
          persistentVolumeClaim:
            claimName: postgres-data-replica
        - configMap:
            items:
              - key: init_replica.sh
                path: init_replica.sh
            name: postgres-replica-cm1
          name: postgres-replica-cm1
