name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Deploy to AWS (or Kubernetes, Docker, etc.)
      run: |
        # Add deployment steps here (e.g., AWS ECS or Kubernetes deployment)
